const STATS_START_YEAR = 2023;

// if these are changed, also change them in public/manifest.json and public/index.html
const MAIN_COLOR = '#000000';
const BRAND_COLOR_LIGHT = '#C1272D';
const BRAND_COLOR_LIGHT_HOVER = '#9E1F24';
const BRAND_COLOR_DARK = '#8B1E23';
const BRAND_COLOR_DARK_HOVER = '#6F181C';

const SNACKBAR_INFO_COLOR_LIGHT = '#DC4D5C';
const SNACKBAR_INFO_COLOR_DARK = '#A62832';

const TEXT_COLOR_LIGHT = '#000000';
const TEXT_COLOR_REVERSED_LIGHT = '#ffffff';
const TEXT_COLOR_REVERSED_LIGHT_HOVER = '#ffffffbf';
const TEXT_COLOR_DARK = '#E2E2E2';
const TEXT_COLOR_SECONDARY_LIGHT = '#666666';
const TEXT_COLOR_SECONDARY_LIGHT_2 = '#808085';
const TEXT_COLOR_SECONDARY_DARK = '#aaaaaa';

const BACKGROUND_COLOR_LIGHT = '#f7f4f1';
const BACKGROUND_COLOR_LIGHT_2 = '#f4f4f4';
const BACKGROUND_COLOR_PURE_LIGHT = '#ffffff';
const BACKGROUND_COLOR_DARK = '#121212';
const BACKGROUND_COLOR_PURE_DARK = '#000000';
const BACKGROUND_COLOR_DARK_2 = '#1E1E1E';
const BACKGROUND_COLOR_DARK_3 = '#2E2E2E';
const BACKGROUND_COLOR_DARK_4 = '#15151E';
const BACKGROUND_COLOR_DARK_5 = '#1f1f28';
const BACKGROUND_COLOR_DARK_5_HOVER = '#2a2a35';
const BACKGROUND_COLOR_DARK_6 = '#363030';
const BACKGROUND_COLOR_DARK_7 = '#494949';
const PAPER_COLOR_LIGHT = '#f7f4f1';
const PAPER_COLOR_DARK = '#1e1e1eff';

const BORDER_COLOR_LIGHT = '#000000';
const BORDER_COLOR_LIGHT_2 = '#C4C4C4';
const BORDER_COLOR_REVERSED_LIGHT = '#ffffff';
const BORDER_COLOR_DARK = '#E2E2E2';
const BORDER_COLOR_REVERSED_DARK = '#5a5a5a';
const BORDER_COLOR_REVERSED_DARK_2 = '#38383f';
const BORDER_COLOR_REVERSED_DARK_3 = '#929292';

const DEFAULT_COMPOUND_COLOR = '#808080';
const SOFT_COMPOUND_COLOR = '#F90021';
const MEDIUM_COMPOUND_COLOR = '#F3C302';
const HARD_COMPOUND_COLOR_LIGHT = '#2F2D2B';
const HARD_COMPOUND_COLOR_DARK = '#6d6c6b';
const INTERMEDIATE_COMPOUND_COLOR = '#019D2E';
const WET_COMPOUND_COLOR = '#2F62A1';
const DEFAULT_COMPOUND_COLOR_RGBA = 'rgb(128,128,128, 0.1)';
const SOFT_COMPOUND_COLOR_RGBA = 'rgb(249, 0, 33, 0.1)';
const MEDIUM_COMPOUND_COLOR_RGBA = 'rgb(243, 195, 2, 0.1)';
const HARD_COMPOUND_COLOR_LIGHT_RGBA = 'rgb(47, 45, 43, 0.1)';
const HARD_COMPOUND_COLOR_DARK_RGBA = 'rgb(109, 108, 107, 0.1)';
const INTERMEDIATE_COMPOUND_COLOR_RGBA = 'rgb(1, 157, 46, 0.1)';
const WET_COMPOUND_COLOR_RGBA = 'rgb(47, 98, 161, 0.1)';

export {
  STATS_START_YEAR,
  MAIN_COLOR,
  BRAND_COLOR_LIGHT,
  BRAND_COLOR_LIGHT_HOVER,
  BRAND_COLOR_DARK,
  BRAND_COLOR_DARK_HOVER,
  SNACKBAR_INFO_COLOR_LIGHT,
  SNACKBAR_INFO_COLOR_DARK,
  TEXT_COLOR_LIGHT,
  TEXT_COLOR_REVERSED_LIGHT,
  TEXT_COLOR_REVERSED_LIGHT_HOVER,
  TEXT_COLOR_DARK,
  TEXT_COLOR_SECONDARY_LIGHT,
  TEXT_COLOR_SECONDARY_LIGHT_2,
  TEXT_COLOR_SECONDARY_DARK,
  BACKGROUND_COLOR_LIGHT,
  BACKGROUND_COLOR_LIGHT_2,
  BACKGROUND_COLOR_PURE_LIGHT,
  BACKGROUND_COLOR_DARK,
  BACKGROUND_COLOR_PURE_DARK,
  BACKGROUND_COLOR_DARK_2,
  BACKGROUND_COLOR_DARK_3,
  BACKGROUND_COLOR_DARK_4,
  BACKGROUND_COLOR_DARK_5,
  BACKGROUND_COLOR_DARK_5_HOVER,
  BACKGROUND_COLOR_DARK_6,
  BACKGROUND_COLOR_DARK_7,
  PAPER_COLOR_LIGHT,
  PAPER_COLOR_DARK,
  BORDER_COLOR_LIGHT,
  BORDER_COLOR_LIGHT_2,
  BORDER_COLOR_REVERSED_LIGHT,
  BORDER_COLOR_DARK,
  BORDER_COLOR_REVERSED_DARK,
  BORDER_COLOR_REVERSED_DARK_2,
  BORDER_COLOR_REVERSED_DARK_3,
  DEFAULT_COMPOUND_COLOR,
  SOFT_COMPOUND_COLOR,
  MEDIUM_COMPOUND_COLOR,
  HARD_COMPOUND_COLOR_LIGHT,
  HARD_COMPOUND_COLOR_DARK,
  INTERMEDIATE_COMPOUND_COLOR,
  WET_COMPOUND_COLOR,
  DEFAULT_COMPOUND_COLOR_RGBA,
  SOFT_COMPOUND_COLOR_RGBA,
  MEDIUM_COMPOUND_COLOR_RGBA,
  HARD_COMPOUND_COLOR_LIGHT_RGBA,
  HARD_COMPOUND_COLOR_DARK_RGBA,
  INTERMEDIATE_COMPOUND_COLOR_RGBA,
  WET_COMPOUND_COLOR_RGBA,
};
