const STATS_START_YEAR = 2023;

// if these are changed, also change them in public/manifest.json and public/index.html
const MAIN_COLOR = '#000000';
const BRAND_COLOR_LIGHT = '#E10600';
const BRAND_COLOR_LIGHT_HOVER = '#b40500';
const BRAND_COLOR_DARK = '#870400';
const BRAND_COLOR_DARK_HOVER = '#6c0300';

const SNACKBAR_INFO_COLOR_LIGHT = '#ff6b6b';
const SNACKBAR_INFO_COLOR_DARK = '#c92a2a';

const TEXT_COLOR_LIGHT = '#000000';
const TEXT_COLOR_REVERSED_LIGHT = '#ffffff';
const TEXT_COLOR_DARK = '#E2E2E2';
const TEXT_COLOR_SECONDARY_LIGHT = '#666666';
const TEXT_COLOR_SECONDARY_DARK = '#aaaaaa';

const BACKGROUND_COLOR_LIGHT = '#f7f4f1';
const BACKGROUND_COLOR_DARK = '#121212';
const PAPER_COLOR_LIGHT = '#f7f4f1';
const PAPER_COLOR_DARK = '#1e1e1eff';

const BORDER_COLOR_LIGHT = '#000000';
const BORDER_COLOR_REVERSED_LIGHT = '#ffffff';
const BORDER_COLOR_DARK = '#E2E2E2';
const BORDER_COLOR_REVERSED_DARK = '#5a5a5a';

export {
  STATS_START_YEAR,
  MAIN_COLOR,
  BRAND_COLOR_LIGHT,
  BRAND_COLOR_LIGHT_HOVER,
  BRAND_COLOR_DARK,
  BRAND_COLOR_DARK_HOVER,
  SNACKBAR_INFO_COLOR_LIGHT,
  SNACKBAR_INFO_COLOR_DARK,
  TEXT_COLOR_LIGHT,
  TEXT_COLOR_REVERSED_LIGHT,
  TEXT_COLOR_DARK,
  TEXT_COLOR_SECONDARY_LIGHT,
  TEXT_COLOR_SECONDARY_DARK,
  BACKGROUND_COLOR_LIGHT,
  BACKGROUND_COLOR_DARK,
  PAPER_COLOR_LIGHT,
  PAPER_COLOR_DARK,
  BORDER_COLOR_LIGHT,
  BORDER_COLOR_REVERSED_LIGHT,
  BORDER_COLOR_DARK,
  BORDER_COLOR_REVERSED_DARK,
};
